apiVersion: v1
kind: Service
metadata:
  name: tools-service
spec:
  type: ClusterIP
  selector:
    app: tools
    component: api
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: api