apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
    component: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http